# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UserNameLineEdit = QtWidgets.QLineEdit(Form)
        self.UserNameLineEdit.setObjectName("UserNameLineEdit")
        self.verticalLayout.addWidget(self.UserNameLineEdit)
        self.PasswordLineEdit = QtWidgets.QLineEdit(Form)
        self.PasswordLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.PasswordLineEdit.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.PasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.verticalLayout.addWidget(self.PasswordLineEdit)
        self.LoginButton = QtWidgets.QPushButton(Form)
        self.LoginButton.setObjectName("LoginButton")
        self.verticalLayout.addWidget(self.LoginButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LoginButton.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
