# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snapshotWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_snapshot(object):
    def setupUi(self, snapshot):
        snapshot.setObjectName("snapshot")
        snapshot.resize(270, 90)
        snapshot.setMinimumSize(QtCore.QSize(270, 90))
        snapshot.setMaximumSize(QtCore.QSize(270, 90))
        self.horizontalLayout = QtWidgets.QHBoxLayout(snapshot)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Image = QtWidgets.QLabel(snapshot)
        self.Image.setMinimumSize(QtCore.QSize(70, 70))
        self.Image.setMaximumSize(QtCore.QSize(70, 70))
        self.Image.setStyleSheet("")
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../resources/img/image-not-found.jpg"))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.horizontalLayout.addWidget(self.Image)
        self.moreButton = QtWidgets.QPushButton(snapshot)
        self.moreButton.setMinimumSize(QtCore.QSize(0, 24))
        self.moreButton.setObjectName("moreButton")
        self.horizontalLayout.addWidget(self.moreButton)
        self.pushButton = QtWidgets.QPushButton(snapshot)
        self.pushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton.setStyleSheet("background-image: url(:/loop/loop.png);\n"
"background-position: center;")
        self.pushButton.setText("")
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(snapshot)
        QtCore.QMetaObject.connectSlotsByName(snapshot)

    def retranslateUi(self, snapshot):
        _translate = QtCore.QCoreApplication.translate
        snapshot.setWindowTitle(_translate("snapshot", "Frame"))
        self.moreButton.setText(_translate("snapshot", "Подробнее"))
import resources.img.Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    snapshot = QtWidgets.QFrame()
    ui = Ui_snapshot()
    ui.setupUi(snapshot)
    snapshot.show()
    sys.exit(app.exec_())
